# Generated by Django 5.2.7 on 2025-10-31 17:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Номер паспорта')),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('occupied', 'Занят'), ('maintenance', 'На обслуживании')], default='available', max_length=20, verbose_name='Статус')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Этаж')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Особенности')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип номера')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Вместимость')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждено'), ('checked_in', 'Заселен'), ('checked_out', 'Выселен'), ('awaiting_payment', 'Ожидает оплаты'), ('cancelled', 'Отменено')], default='awaiting_payment', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Особые пожелания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.customer', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.room', verbose_name='Комната')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Картой'), ('cash', 'Наличными'), ('on_site', 'На сайте')], default='credit_card', max_length=50, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершен'), ('failed', 'Неудачный'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.booking', verbose_name='Бронирование')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.roomtype', verbose_name='Тип номера'),
        ),
    ]
