# Generated by Django 6.0.1 on 2026-03-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleaning_status',
            field=models.CharField(choices=[('clean', 'Чистый'), ('dirty', 'Грязный')], default='clean', max_length=20, verbose_name='Статус уборки'),
        ),
    ]
