# Generated by Django 6.0.1 on 2026-03-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_room_cleaning_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='cleaning_status',
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('checkout', 'После выезда'), ('checkin', 'Подготовка к заезду'), ('linen_change', 'Смена белья'), ('daily', 'Поддерживающая')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Выполнена')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.room', verbose_name='Номер')),
            ],
            options={
                'unique_together': {('room', 'task_type', 'scheduled_date')},
            },
        ),
    ]
