# Generated by Django 6.0.1 on 2026-03-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_room_cleaning_status_cleaningtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CleaningTask',
        ),
    ]
