# Generated by Django 6.0.1 on 2026-01-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mean_booking_hours',
            field=models.IntegerField(choices=[(1, 'За 1 час'), (2, 'За 2 часа'), (3, 'За 3 часа'), (6, 'За 6 часов'), (12, 'За 12 часов'), (24, 'За 24 часа'), (48, 'За 48 часов'), (72, 'За 72 часа (3 дня)'), (168, 'За 1 неделю'), (0, 'Можно бронировать в любое время')], default=3, help_text='Минимальное время, за которое можно забронировать услугу', verbose_name='Можно бронировать за'),
        ),
    ]
