# Generated by Django 6.0.1 on 2026-01-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_mean_booking_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='mean_booking_hours',
            new_name='min_booking_hours',
        ),
    ]
