# Generated by Django 6.0.1 on 2026-05-23 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_mean_booking_hours_service_min_booking_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Цвет шахматки')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('services', models.ManyToManyField(related_name='specialists', to='service.service', verbose_name='Услуги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_specialist', to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись')),
            ],
            options={
                'verbose_name': 'Специалист услуг',
                'verbose_name_plural': 'Специалисты услуг',
                'ordering': ['user__last_name', 'user__first_name', 'user__username'],
            },
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='service.servicespecialist', verbose_name='Специалист'),
        ),
    ]
