# Generated by Django 6.0.1 on 2026-04-26 15:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0004_delete_cleaningtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Housekeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('color', models.CharField(default='#667eea', max_length=7, verbose_name='Цвет в интерфейсе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeper', to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись')),
            ],
            options={
                'verbose_name': 'Горничная',
                'verbose_name_plural': 'Горничные',
            },
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('cleaning_type', models.CharField(choices=[('current', 'Текущая уборка'), ('general', 'Генеральная уборка'), ('unsheduled', 'Внеплановая уборка')], default='current', max_length=20, verbose_name='Вид уборки')),
                ('duration_min', models.IntegerField(default=20, verbose_name='Подготовка (мин)')),
                ('state', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('done', 'Выполнено'), ('verified', 'Проверено')], default='pending', max_length=20, verbose_name='Состояние')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cleaning_tasks', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to='admin_panel.room', verbose_name='Номер')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='housekeeping.housekeeper', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задание на уборку',
                'verbose_name_plural': 'Задания на уборку',
                'ordering': ['date', 'room__room_number'],
            },
        ),
        migrations.CreateModel(
            name='RepairTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('state', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('done', 'Выполнено')], default='pending', max_length=20, verbose_name='Состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_tasks', to='housekeeping.housekeeper', verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_repair_tasks', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_tasks', to='admin_panel.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Заявка на ремонт',
                'verbose_name_plural': 'Заявки на ремонт',
                'ordering': ['date', 'room__room_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('dirty', 'Грязный'), ('cleaned', 'Убрано'), ('verified', 'Проверено'), ('repair', 'Ремонт')], default='verified', max_length=20, verbose_name='Состояние')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Обновлено')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clean_state', to='admin_panel.room', verbose_name='Номер')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем')),
            ],
            options={
                'verbose_name': 'Состояние номера',
                'verbose_name_plural': 'Состояние номеров',
            },
        ),
    ]
