# Generated by Django 6.0.1 on 2026-05-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtask',
            name='cleaning_type',
            field=models.CharField(choices=[('current', 'Текущая уборка'), ('general', 'Генеральная уборка'), ('unscheduled', 'Внеплановая уборка'), ('move_in', 'Уборка при заезде'), ('departure', 'Уборка при выезде')], default='current', max_length=20, verbose_name='Вид уборки'),
        ),
    ]
